apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-application
spec:
  replicas: 1 # Number of replicas
  selector:
    matchLabels:
      app: my-application
  template:
    metadata:
      labels:
        app: my-application
    spec:
      initContainers:
      - name: init-cert-conversion
        image: registry.digitalocean.com/qwerty/imagination:latest
        command: ["/bin/bash", "-c", "/tmp/convert_cert.sh"]
      containers:
      - name: my-application
        image: registry.digitalocean.com/qwerty/imagination:latest # Use your image path
        imagePullPolicy: Always #because I am using latest tag, setting this to instruct kubernetes to always pull a new image
        ports:
        - containerPort: 80 # Adjust based on your application's needs