apiVersion: v1
kind: Service
metadata:
  name: my-application-service
spec:
  type: LoadBalancer
  selector:
    app: my-application
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 # Ensure this matches the containerPort in your deployment
