apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: apache-service-monitor
  namespace: monitoring
  labels:
    release: prometheus  # This matches your Prometheus Helm release name
spec:
  selector:
    matchLabels:
      app: my-application  # Ensure this matches the labels of your Apache service
  namespaceSelector:
    matchNames:
    - default  # Assuming your Apache service is in the default namespace
  endpoints:
  - port: http  # Ensure this matches the named port in your Service, if defined, or use the containerPort number
    path: "/server-status"
    interval: "30s"
    params:
      auto: ['1']  # Query parameter for mod_status to return machine-readable format
