apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: apache-service-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: my-application
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: http
    path: "/server-status"
    interval: "30s"
    params:
      auto: ['1']  # Query parameter for mod_status to return machine-readable format
